# Generated by Django 5.0.3 on 2024-03-23 14:47

import mdeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_slug', models.SlugField(max_length=200, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Labs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_slug', models.SlugField(max_length=1000, unique=True)),
                ('lab_title', models.CharField(max_length=1000)),
                ('lab_sub_title', models.TextField(blank=True, null=True)),
                ('lab_image', models.ImageField(blank=True, null=True, upload_to='labs_images/')),
                ('lab_youtube_id', models.CharField(blank=True, max_length=1000, null=True)),
                ('lab_content', mdeditor.fields.MDTextField()),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('lab_tags', models.ManyToManyField(related_name='labs_tags', to='home.tags')),
            ],
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_slug', models.SlugField(max_length=1000, unique=True)),
                ('course_title', models.CharField(max_length=1000)),
                ('course_sub_title', models.CharField(max_length=2000)),
                ('course_image', models.ImageField(blank=True, null=True, upload_to='courses_images/')),
                ('course_content', mdeditor.fields.MDTextField()),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('course_tags', models.ManyToManyField(related_name='courses_tags', to='home.tags')),
            ],
        ),
    ]
