# Generated by Django 5.0.3 on 2024-03-24 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='tag_background_color',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tags',
            name='tag_text_color',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
