# Generated by Django 5.0.3 on 2024-03-17 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='course_name',
        ),
    ]
