# Generated by Django 5.0.3 on 2024-03-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_courses_course_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='labs',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
