# Generated by Django 5.0.3 on 2024-03-20 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_courses_course_image_alter_labs_lab_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='tag_name',
        ),
    ]
