# Generated by Django 5.0.3 on 2024-03-20 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_remove_tags_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='course_image',
            field=models.ImageField(blank=True, null=True, upload_to='courses_images'),
        ),
        migrations.AlterField(
            model_name='labs',
            name='lab_image',
            field=models.ImageField(blank=True, null=True, upload_to='labs_images'),
        ),
    ]
