# Generated by Django 5.0.3 on 2024-03-21 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_courses_course_image_alter_labs_lab_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labs',
            name='lab_name',
        ),
        migrations.AddField(
            model_name='labs',
            name='lab_sub_title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
