# Generated by Django 5.0.3 on 2024-03-21 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_labs_lab_name_labs_lab_sub_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='labs',
            name='lab_tags',
            field=models.ManyToManyField(related_name='labs_tags', to='home.tags'),
        ),
    ]
