# Generated by Django 5.0.3 on 2024-03-21 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_labs_lab_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='labs',
            name='lab_youtube_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
